### ISSUE TITLE
Check for working CXX compiler: /opt/rocm/hip/bin/hipcc - broken

### ISSUE THREAD

**Issue by petronny** [rocm-arch/rocm-arch#468]
This error occurs when building `rccl`, `miopen-hip` and `rocalution`.

```
==> Starting build()...
-- The CXX compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /opt/rocm/hip/bin/hipcc
-- Check for working CXX compiler: /opt/rocm/hip/bin/hipcc - broken
CMake Error at /usr/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/opt/rocm/hip/bin/hipcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /build/rccl/src/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_74818/fast && /usr/bin/make  -f CMakeFiles/cmTC_74818.dir/build.make CMakeFiles/cmTC_74818.dir/build
    make[1]: Entering directory '/build/rccl/src/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_74818.dir/testCXXCompiler.cxx.o
    /opt/rocm/hip/bin/hipcc   -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -o CMakeFiles/cmTC_74818.dir/testCXXCompiler.cxx.o -c /build/rccl/src/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    clang-12: error: cannot find HIP runtime. Provide its path via --rocm-path, or pass -nogpuinc to build without HIP runtime.
    clang-12: error: cannot find HIP runtime. Provide its path via --rocm-path, or pass -nogpuinc to build without HIP runtime.
    make[1]: *** [CMakeFiles/cmTC_74818.dir/build.make:85: CMakeFiles/cmTC_74818.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory '/build/rccl/src/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_74818/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)


-- Configuring incomplete, errors occurred!
See also "/build/rccl/src/build/CMakeFiles/CMakeOutput.log".
See also "/build/rccl/src/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
```

**Comment by skrax** [comment]
This is the error cause:
``
clang-12: error: cannot find HIP runtime. Provide its path via --rocm-path, or pass -nogpuinc to build without HIP runtime.
``

You need to set the --rocm-path flag when invoking the compiler, see #466 .

For now you can adjust the buildscripts of the package you are trying to build, by adding this line to the cmake invokation in PKBUILD:

``
-DCMAKE_CXX_FLAGS=--rocm-path=/opt/rocm \
``

**Comment by Hufschmidt** [comment]
While this helps, building r`oc-blas` sadly still fails due to Tensile not knowing about correct rocm-path. :sob:

Lets see if I can find something to pass it along (or simply put it into its own CMakeLists.txt). Is there no way to define this globally like CXX, CXX_FLAGS?
Sadly Tensil does not know about `rocm-blas`'s CMAKE_CXX_FLAGS settings...

**Comment by Hufschmidt** [comment]
Ok, I got it working and compiling:

* Option a: Disable Tensile using `-DBUILD_WITH_TENSILE=OFF` and dropping any Tensile related settings.
  As far as I can tell Tensile is used to select the best kernel for blas, so this might lead to worse performance...
* Option b: Link against locally patched Tensile version using `-DTensile_TEST_LOCAL_PATH=<path to local git clone>`

Patch against Tensile Tag **rocm-3.9.0**:
```patch
diff --git a/Tensile/ClientExecutable.py b/Tensile/ClientExecutable.py
index f163b8f9..ffca904a 100644
--- a/Tensile/ClientExecutable.py
+++ b/Tensile/ClientExecutable.py
@@ -60,6 +60,7 @@ def clientExecutableEnvironment(builddir=None):
     options = {'CMAKE_BUILD_TYPE': globalParameters["CMakeBuildType"],
                'TENSILE_NEW_CLIENT': 'ON',
                'Tensile_LIBRARY_FORMAT': globalParameters["LibraryFormat"],
+               'CMAKE_CXX_FLAGS': '--rocm-path=/opt/rocm',
                'CMAKE_CXX_COMPILER': os.path.join('/opt/rocm/bin/', globalParameters['CxxCompiler'])}
 
     return CMakeEnvironment(sourcedir, builddir, **options)
diff --git a/Tensile/Source/client/CMakeLists.txt b/Tensile/Source/client/CMakeLists.txt
index 9ccba862..bf4b7c8a 100644
--- a/Tensile/Source/client/CMakeLists.txt
+++ b/Tensile/Source/client/CMakeLists.txt
@@ -32,7 +32,7 @@ if(NOT ROCmSMI_FOUND)
     find_package(ROCmSMI REQUIRED)
 endif()
 
-target_include_directories(TensileClient PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")# "${rocm_smi_root}/include")
+target_include_directories(TensileClient PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include" "/opt/rocm/rocm_smi/include/")# "${rocm_smi_root}/include")
 
 if(CXX_VERSION_STRING MATCHES "clang")
     target_compile_options(TensileClient PUBLIC -mno-xnack)
diff --git a/Tensile/TensileCreateLibrary.py b/Tensile/TensileCreateLibrary.py
index ac933340..f06a922f 100644
--- a/Tensile/TensileCreateLibrary.py
+++ b/Tensile/TensileCreateLibrary.py
@@ -169,7 +169,7 @@ def buildSourceCodeObjectFile(CxxCompiler, outputPath, kernelFile):
 
       hipFlags = ["--genco", "-D__HIP_HCC_COMPAT_MODE__=1"] #needs to be fixed when Maneesh's change is made available
 
-      hipFlags += ['-I', outputPath]
+      hipFlags += ['-I', outputPath, '--rocm-path=/opt/rocm']
 
       archFlags += ['-mno-xnack', '-Xarch_gfx906', '-msram-ecc', '-Xarch_gfx908', '-msram-ecc']
diff --git a/Tensile/cmake/TensileConfig.cmake b/Tensile/cmake/TensileConfig.cmake
index 07701d96..8cb336cc 100644
--- a/Tensile/cmake/TensileConfig.cmake
+++ b/Tensile/cmake/TensileConfig.cmake
@@ -21,6 +21,8 @@
 
 include(CMakeParseArguments)
 
+set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --rocm-path=/opt/rocm" )
+
 if(NOT DEFINED Tensile_ROOT)
 # Compute the installation prefix relative to this file.
 get_filename_component(Tensile_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
diff --git a/Tensile/cmake/TensileConfigVersion.cmake b/Tensile/cmake/TensileConfigVersion.cmake
index e707e9c0..ab70d4a6 100644
--- a/Tensile/cmake/TensileConfigVersion.cmake
+++ b/Tensile/cmake/TensileConfigVersion.cmake
@@ -24,6 +24,8 @@ set(TENSILE_VERSION_MAJOR  4)
 set(TENSILE_VERSION_MINOR 23)
 set(TENSILE_VERSION_PATCH  0)
 
+set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --rocm-path=/opt/rocm" )
+
 # export version
 set(PACKAGE_VERSION "${TENSILE_VERSION_MAJOR}.${TENSILE_VERSION_MINOR}.${TENSILE_VERSION_PATCH}")
```

**Comment by Hufschmidt** [comment]
I was able to build and install most dependencies from `rocm-libs` using this solution:

```
  cmake
      [...]
        -DCMAKE_CXX_COMPILER=/opt/rocm/hip/bin/hipcc \
        -DCMAKE_CXX_FLAGS=--rocm-path=/opt/rocm
```

There were some minor compilation-related issued with some packages as well, but nothing major...

I'm still new to rocm, but I feel like there is something wrong with the default configuration of either the `llvm-amdgpu` or the `hip-rocclr` package, because from all my google searches `/opt/rocm` should be the default location and should also we overwriteable by ROCM_PATH (and ROCM_ROOT) environment variables globally, but this does not seem to work here...

Maybe I could cross-check this with official packages for Ubuntu running in Docker...

**Comment by Hufschmidt** [comment]
Yes, building a little [example](https://github.com/ROCm-Developer-Tools/HIP/tree/master/samples/0_Intro/bit_extract) project with hipcc inside the ROCm docker-image works without any error.

Building the same example on arch fails with unknown HIP-runtime location unless explicitly adding `--rocm-path=/opt/rocm` to the Makefile...

**Comment by Hufschmidt** [comment]
Is there a way to find cmake flags used to build llvm?

**Comment by skrax** [comment]
If you increase the verbosity level, with
```export HIPCC_VERBOSE=7```,
 you can see that ROCM_PATH is set, however --rocm-path is not passed by default when calling hipcc.

You can edit hipcc and simply append the flag:
```
sudo vim /opt/rocm/hip/bin/hipcc
```
I added it after line 874:
```vim
 $CMD .= " $toolArgs";
 $CMD .= " --rocm-path=/opt/rocm";
```
Of course this is not recommended and does not fix the issue.
I am still finding out, how to change it with CMake directly, so you don't have to do this!

**Comment by Hufschmidt** [comment]
Yeah, that is indeed a possible workaround for `hipcc` itself. (May that what the official Ubuntu packages are doing? Have to check this...)

My main issue currently is, that `tensorflow-rocm` is unusable (Testing with [tf_cnn_benchmark](https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks)), because `miopen-hip` calls `clang++` directly (_as far as I can tell_) when compiling tensorflow kernels, thus also failing with missing `rocm-path` as well.

Now I'm not sure if this is a issue with the way `miopen-hip` is being build/configured (Should it use `hipcc` instead of `clang++` directly?) or if the amdgpu version of `clang++` was misconfigured during build.

**Comment by Hufschmidt** [comment]
In regards to `miopen-hip`, [this](https://github.com/rocm-arch/rocm-arch/blob/master/miopen-hip/PKGBUILD#L25) might be the culprit:

```
  cmake [...]
        -DMIOPEN_HIP_COMPILER=/opt/rocm/llvm/bin/clang++ \
        [...]
```

I think this should actually point to the `hipcc` wrapper instead of `clang++` directly...

**Comment by acxz** [comment]
The above mentioned PR should resolve the issue, but if anyone is still experiencing issues, please post (with potentially updated error logs) so we can continue debugging.
