### ISSUE TITLE
GFX 1012 support

### ISSUE THREAD

**Issue by laclcia** [rocm-arch/rocm-arch#592]
hello. i dont know if i am just not doing thing's properly or if my gpu just isnt supported by ROCm.  also sorry for my poor english i am not a native speaker.
system: manjaro
cpu: Ryzen 7 3700X
ram:32 GB
GPU: GFX 1012(5500XT)
i have followed the instructions of installing the prebuilt binaries from arch4edu
`rocm-dev rocm-utils rocm-libs`
what work's:
basic opengl work's on mandelbulber and other pure opencl softwares i have tested. so at the verry least the opencl driver part work's fine.

what dosent work:
anything saying it requires ROCm like the ROCM build of pytorch or tensorflow gives the error 

`"hipErrorNoBinaryForGpu: Coudn't find binary for current devices!"`

i am mainly interested in pytorch as i can reliably use plaidml for tensorflow. so here is what i have tried. (uninstalling a packadge before trying the next as to not cause problem's)
building from the aur the packadge "python-pytorch-rocm" and the packadge "python-pytorch-opt-rocm"
installing the official pytorch ROCM using pip
all of thease gives me the same error when i try using them. (or when i subsequently try to install torchvision)

at this point i am either doing something wrong or my gpu isnt supported yet. i hope it's just me not doing something properly like not setting an environement variable or missing a packadge or something. 

thank you for your time.

**Comment by tpkessler** [comment]
>  so at the verry least the opencl driver part work's fine.

Yes, and that's basically all that is known to work. `hip-rocclr` includes a patch for `hip-config.cmake`, a file which includes the list of officially supported GPUs, `AMDGPU_TARGETS`, is defined. You may add `gfx1012` to that list but the last time I tried that it didn't work: All packages in `rocm-libs` did not compile as they missed support for Navi.

In addition, please note that we do not support manjaro, so the ROCm packages for Arch Linux may not work with your distro.

**Comment by hedgepigdaniel** [comment]
> Yes, and that's basically all that is known to work. `hip-rocclr` includes a patch for `hip-config.cmake`, a file which includes the list of officially supported GPUs, `AMDGPU_TARGETS`, is defined. You may add `gfx1012` to that list but the last time I tried that it didn't work: All packages in `rocm-libs` did not compile as they missed support for Navi.

I can't see any patches in `hip-rocclr`, and the [only thing in the PKGBUILD](https://github.com/rocm-arch/rocm-arch/blob/1cd2da35e343e3205fcbc25b350f35b4d6e25026/hip-rocclr/PKGBUILD#L33) about specific GPU's doesn't seem to involve Navi GPUs.

However, I have a 5600XT and I can confirm that it works - with `rocm-opencl-runtime` I can successfully run an application using OpenCL through OpenCV, including some of its common algorithms as well as some of my own kernels.

**Comment by tpkessler** [comment]
> I can't see any patches in hip-rocclr

Yes, I removed the patch since AMD dropped support for gfx803,

https://github.com/RadeonOpenCompute/ROCm/issues/1353#issuecomment-753772733

Albeit not officially supported, HIP is also known to work with Navi and most packages in `rocm-libs` explicitly generate code for Navi.

**Comment by serhii-nakon** [comment]
@tpkessler @laclcia Hello, here Docker container that have working Pytorch 2.2 and ROCm 5.4 https://hub.docker.com/r/serhiin/rocm_gfx1012_pytorch also repository with patches https://github.com/serhii-nakon/rocm_gfx1012_pytorch

I would like if arch linux prebuilt ROCm for whole rx5000 if it possible.
